DROP PROCEDURE ZENDSVR6.iPLUG4K;
DROP PROCEDURE ZENDSVR6.iPLUG32K;
DROP PROCEDURE ZENDSVR6.iPLUG65K;
DROP PROCEDURE ZENDSVR6.iPLUG512K;
DROP PROCEDURE ZENDSVR6.iPLUG1M;
DROP PROCEDURE ZENDSVR6.iPLUG5M;
DROP PROCEDURE ZENDSVR6.iPLUG10M;
DROP PROCEDURE ZENDSVR6.iPLUG15M;

DROP PROCEDURE ZENDSVR6.iPLUGR4K;
DROP PROCEDURE ZENDSVR6.iPLUGR32K;
DROP PROCEDURE ZENDSVR6.iPLUGR65K;
DROP PROCEDURE ZENDSVR6.iPLUGR512K;
DROP PROCEDURE ZENDSVR6.iPLUGR1M;
DROP PROCEDURE ZENDSVR6.iPLUGR5M;
DROP PROCEDURE ZENDSVR6.iPLUGR10M;
DROP PROCEDURE ZENDSVR6.iPLUGR15M;

DROP PROCEDURE ZENDSVR6.iBLOB4K;
DROP PROCEDURE ZENDSVR6.iBLOB32K;
DROP PROCEDURE ZENDSVR6.iBLOB65K;
DROP PROCEDURE ZENDSVR6.iBLOB512K;
DROP PROCEDURE ZENDSVR6.iBLOB1M;
DROP PROCEDURE ZENDSVR6.iBLOB5M;
DROP PROCEDURE ZENDSVR6.iBLOB10M;
DROP PROCEDURE ZENDSVR6.iBLOB15M;

DROP PROCEDURE ZENDSVR6.iBLOBR4K;
DROP PROCEDURE ZENDSVR6.iBLOBR32K;
DROP PROCEDURE ZENDSVR6.iBLOBR65K;
DROP PROCEDURE ZENDSVR6.iBLOBR512K;
DROP PROCEDURE ZENDSVR6.iBLOBR1M;
DROP PROCEDURE ZENDSVR6.iBLOBR5M;
DROP PROCEDURE ZENDSVR6.iBLOBR10M;
DROP PROCEDURE ZENDSVR6.iBLOBR15M;

DROP PROCEDURE ZENDSVR6.iPLUGRC32K;

CREATE PROCEDURE ZENDSVR6.iPLUG4K(
IN IPC CHAR(1024), IN CTL CHAR(1024),
IN CI CLOB(4K), OUT C0 CLOB(4K))
LANGUAGE RPGLE 
NOT DETERMINISTIC
MODIFIES SQL DATA
EXTERNAL NAME 'ZENDSVR6/XMLSTOREDP(iPLUG4K)'
PARAMETER STYLE GENERAL;

CREATE PROCEDURE ZENDSVR6.iPLUG32K(
IN IPC CHAR(1024), IN CTL CHAR(1024), 
IN CI CLOB(32K), OUT CO CLOB(32K)) 
LANGUAGE RPGLE NOT DETERMINISTIC 
MODIFIES SQL DATA 
EXTERNAL NAME 'ZENDSVR6/XMLSTOREDP(iPLUG32K)' 
PARAMETER STYLE GENERAL;

CREATE PROCEDURE ZENDSVR6.iPLUG65K(
IN IPC CHAR(1024), IN CTL CHAR(1024), 
IN CI CLOB(65K), OUT CO CLOB(65K)) 
LANGUAGE RPGLE NOT DETERMINISTIC 
MODIFIES SQL DATA 
EXTERNAL NAME 'ZENDSVR6/XMLSTOREDP(iPLUG65K)' 
PARAMETER STYLE GENERAL;

CREATE PROCEDURE ZENDSVR6.iPLUG512K(
IN IPC CHAR(1024), IN CTL CHAR(1024), 
IN CI CLOB(512K), OUT CO CLOB(512K)) 
LANGUAGE RPGLE NOT DETERMINISTIC 
MODIFIES SQL DATA 
EXTERNAL NAME 'ZENDSVR6/XMLSTOREDP(iPLUG512K)' 
PARAMETER STYLE GENERAL;

CREATE PROCEDURE ZENDSVR6.iPLUG1M(
IN IPC CHAR(1024), IN CTL CHAR(1024), 
IN CI CLOB(1M), OUT CO CLOB(1M)) 
LANGUAGE RPGLE NOT DETERMINISTIC 
MODIFIES SQL DATA 
EXTERNAL NAME 'ZENDSVR6/XMLSTOREDP(iPLUG1M)' 
PARAMETER STYLE GENERAL;

CREATE PROCEDURE ZENDSVR6.iPLUG5M(
IN IPC CHAR(1024), IN CTL CHAR(1024), 
IN CI CLOB(5M), OUT CO CLOB(5M)) 
LANGUAGE RPGLE NOT DETERMINISTIC 
MODIFIES SQL DATA 
EXTERNAL NAME 'ZENDSVR6/XMLSTOREDP(iPLUG5M)' 
PARAMETER STYLE GENERAL;

CREATE PROCEDURE ZENDSVR6.iPLUG10M(
IN IPC CHAR(1024), IN CTL CHAR(1024), 
IN CI CLOB(10M), OUT CO CLOB(10M)) 
LANGUAGE RPGLE NOT DETERMINISTIC 
MODIFIES SQL DATA 
EXTERNAL NAME 'ZENDSVR6/XMLSTOREDP(iPLUG10M)' 
PARAMETER STYLE GENERAL;

CREATE PROCEDURE ZENDSVR6.iPLUG15M(
IN IPC CHAR(1024), IN CTL CHAR(1024), 
IN CI CLOB(15M), OUT CO CLOB(15M)) 
LANGUAGE RPGLE NOT DETERMINISTIC 
MODIFIES SQL DATA 
EXTERNAL NAME 'ZENDSVR6/XMLSTOREDP(iPLUG15M)' 
PARAMETER STYLE GENERAL;


CREATE PROCEDURE ZENDSVR6.iPLUGR4K(
IN IPC CHAR(1024), IN CTL CHAR(1024), 
IN CI CLOB(4K)) 
LANGUAGE RPGLE NOT DETERMINISTIC 
MODIFIES SQL DATA 
Result Sets 1 
EXTERNAL NAME 'ZENDSVR6/XMLSTOREDP(iPLUGR4K)' 
PARAMETER STYLE GENERAL;

CREATE PROCEDURE ZENDSVR6.iPLUGR32K(
IN IPC CHAR(1024), IN CTL CHAR(1024), 
IN CI CLOB(32K)) 
LANGUAGE RPGLE NOT DETERMINISTIC 
MODIFIES SQL DATA 
Result Sets 1 
EXTERNAL NAME 'ZENDSVR6/XMLSTOREDP(iPLUGR32K)' 
PARAMETER STYLE GENERAL;

CREATE PROCEDURE ZENDSVR6.iPLUGR65K(
IN IPC CHAR(1024), IN CTL CHAR(1024), 
IN CI CLOB(65K)) 
LANGUAGE RPGLE NOT DETERMINISTIC 
MODIFIES SQL DATA 
Result Sets 1 
EXTERNAL NAME 'ZENDSVR6/XMLSTOREDP(iPLUGR65K)' 
PARAMETER STYLE GENERAL;

CREATE PROCEDURE ZENDSVR6.iPLUGR512K(
IN IPC CHAR(1024), IN CTL CHAR(1024), 
IN CI CLOB(512K)) 
LANGUAGE RPGLE NOT DETERMINISTIC 
MODIFIES SQL DATA 
Result Sets 1 
EXTERNAL NAME 'ZENDSVR6/XMLSTOREDP(iPLUGR512K)' 
PARAMETER STYLE GENERAL;

CREATE PROCEDURE ZENDSVR6.iPLUGR1M(
IN IPC CHAR(1024), IN CTL CHAR(1024), 
IN CI CLOB(1M)) 
LANGUAGE RPGLE NOT DETERMINISTIC 
MODIFIES SQL DATA 
Result Sets 1 
EXTERNAL NAME 'ZENDSVR6/XMLSTOREDP(iPLUGR1M)' 
PARAMETER STYLE GENERAL;

CREATE PROCEDURE ZENDSVR6.iPLUGR5M(
IN IPC CHAR(1024), IN CTL CHAR(1024), 
IN CI CLOB(5M)) 
LANGUAGE RPGLE NOT DETERMINISTIC 
MODIFIES SQL DATA 
Result Sets 1 
EXTERNAL NAME 'ZENDSVR6/XMLSTOREDP(iPLUGR5M)' 
PARAMETER STYLE GENERAL;

CREATE PROCEDURE ZENDSVR6.iPLUGR10M(
IN IPC CHAR(1024), IN CTL CHAR(1024), 
IN CI CLOB(10M)) 
LANGUAGE RPGLE NOT DETERMINISTIC 
MODIFIES SQL DATA 
Result Sets 1 
EXTERNAL NAME 'ZENDSVR6/XMLSTOREDP(iPLUGR10M)' 
PARAMETER STYLE GENERAL;

CREATE PROCEDURE ZENDSVR6.iPLUGR15M(
IN IPC CHAR(1024), IN CTL CHAR(1024), 
IN CI CLOB(15M)) 
LANGUAGE RPGLE NOT DETERMINISTIC 
MODIFIES SQL DATA 
Result Sets 1 
EXTERNAL NAME 'ZENDSVR6/XMLSTOREDP(iPLUGR15M)' 
PARAMETER STYLE GENERAL;


CREATE PROCEDURE ZENDSVR6.iBLOB512K(
IN IPC CHAR(1024), IN CTL CHAR(1024), 
IN CI BLOB(512K), OUT CO BLOB(512K)) 
LANGUAGE RPGLE NOT DETERMINISTIC 
MODIFIES SQL DATA 
EXTERNAL NAME 'ZENDSVR6/XMLSTOREDP(iPLUG512K)' 
PARAMETER STYLE GENERAL;

CREATE PROCEDURE ZENDSVR6.iBLOB1M(
IN IPC CHAR(1024), IN CTL CHAR(1024), 
IN CI BLOB(1M), OUT CO BLOB(1M)) 
LANGUAGE RPGLE NOT DETERMINISTIC 
MODIFIES SQL DATA 
EXTERNAL NAME 'ZENDSVR6/XMLSTOREDP(iPLUG1M)' 
PARAMETER STYLE GENERAL;

CREATE PROCEDURE ZENDSVR6.iBLOB5M(
IN IPC CHAR(1024), IN CTL CHAR(1024), 
IN CI BLOB(5M), OUT CO BLOB(5M)) 
LANGUAGE RPGLE NOT DETERMINISTIC 
MODIFIES SQL DATA 
EXTERNAL NAME 'ZENDSVR6/XMLSTOREDP(iPLUG5M)' 
PARAMETER STYLE GENERAL;

CREATE PROCEDURE ZENDSVR6.iBLOB10M(
IN IPC CHAR(1024), IN CTL CHAR(1024), 
IN CI BLOB(10M), OUT CO BLOB(10M)) 
LANGUAGE RPGLE NOT DETERMINISTIC 
MODIFIES SQL DATA 
EXTERNAL NAME 'ZENDSVR6/XMLSTOREDP(iPLUG10M)' 
PARAMETER STYLE GENERAL;

CREATE PROCEDURE ZENDSVR6.iBLOB15M(
IN IPC CHAR(1024), IN CTL CHAR(1024), 
IN CI BLOB(15M), OUT CO BLOB(15M)) 
LANGUAGE RPGLE NOT DETERMINISTIC 
MODIFIES SQL DATA 
EXTERNAL NAME 'ZENDSVR6/XMLSTOREDP(iPLUG15M)' 
PARAMETER STYLE GENERAL;

CREATE PROCEDURE ZENDSVR6.iBLOBR512K(
IN IPC CHAR(1024), IN CTL CHAR(1024), 
IN CI BLOB(512K)) 
LANGUAGE RPGLE NOT DETERMINISTIC 
MODIFIES SQL DATA 
Result Sets 1 
EXTERNAL NAME 'ZENDSVR6/XMLSTOREDP(iPLUGR512K)' 
PARAMETER STYLE GENERAL;

CREATE PROCEDURE ZENDSVR6.iBLOBR1M(
IN IPC CHAR(1024), IN CTL CHAR(1024), 
IN CI BLOB(1M)) 
LANGUAGE RPGLE NOT DETERMINISTIC 
MODIFIES SQL DATA 
Result Sets 1 
EXTERNAL NAME 'ZENDSVR6/XMLSTOREDP(iPLUGR1M)' 
PARAMETER STYLE GENERAL;

CREATE PROCEDURE ZENDSVR6.iBLOBR5M(
IN IPC CHAR(1024), IN CTL CHAR(1024), 
IN CI BLOB(5M)) 
LANGUAGE RPGLE NOT DETERMINISTIC 
MODIFIES SQL DATA 
Result Sets 1 
EXTERNAL NAME 'ZENDSVR6/XMLSTOREDP(iPLUGR5M)' 
PARAMETER STYLE GENERAL;

CREATE PROCEDURE ZENDSVR6.iBLOBR10M(
IN IPC CHAR(1024), IN CTL CHAR(1024), 
IN CI BLOB(10M)) 
LANGUAGE RPGLE NOT DETERMINISTIC 
MODIFIES SQL DATA 
Result Sets 1 
EXTERNAL NAME 'ZENDSVR6/XMLSTOREDP(iPLUGR10M)' 
PARAMETER STYLE GENERAL;

CREATE PROCEDURE ZENDSVR6.iBLOBR15M(
IN IPC CHAR(1024), IN CTL CHAR(1024), 
IN CI BLOB(15M)) 
LANGUAGE RPGLE NOT DETERMINISTIC 
MODIFIES SQL DATA 
Result Sets 1 
EXTERNAL NAME 'ZENDSVR6/XMLSTOREDP(iPLUGR15M)' 
PARAMETER STYLE GENERAL;


CREATE PROCEDURE ZENDSVR6.iPLUGRC32K(
IN IPC CHAR(1024), IN CTL CHAR(1024), 
IN CI VARCHAR(32700), IN CNT INTEGER) 
LANGUAGE RPGLE NOT DETERMINISTIC 
MODIFIES SQL DATA 
Result Sets 1 
EXTERNAL NAME 'ZENDSVR6/XMLSTOREDP(iPLUGRC32K)' 
PARAMETER STYLE GENERAL;



