DROP PROCEDURE QXMLSERV.iPLUG4K;
DROP PROCEDURE QXMLSERV.iPLUG32K;
DROP PROCEDURE QXMLSERV.iPLUG65K;
DROP PROCEDURE QXMLSERV.iPLUG512K;
DROP PROCEDURE QXMLSERV.iPLUG1M;
DROP PROCEDURE QXMLSERV.iPLUG5M;
DROP PROCEDURE QXMLSERV.iPLUG10M;
DROP PROCEDURE QXMLSERV.iPLUG15M;

DROP PROCEDURE QXMLSERV.iPLUGR4K;
DROP PROCEDURE QXMLSERV.iPLUGR32K;
DROP PROCEDURE QXMLSERV.iPLUGR65K;
DROP PROCEDURE QXMLSERV.iPLUGR512K;
DROP PROCEDURE QXMLSERV.iPLUGR1M;
DROP PROCEDURE QXMLSERV.iPLUGR5M;
DROP PROCEDURE QXMLSERV.iPLUGR10M;
DROP PROCEDURE QXMLSERV.iPLUGR15M;

DROP PROCEDURE QXMLSERV.iBLOB4K;
DROP PROCEDURE QXMLSERV.iBLOB32K;
DROP PROCEDURE QXMLSERV.iBLOB65K;
DROP PROCEDURE QXMLSERV.iBLOB512K;
DROP PROCEDURE QXMLSERV.iBLOB1M;
DROP PROCEDURE QXMLSERV.iBLOB5M;
DROP PROCEDURE QXMLSERV.iBLOB10M;
DROP PROCEDURE QXMLSERV.iBLOB15M;

DROP PROCEDURE QXMLSERV.iBLOBR4K;
DROP PROCEDURE QXMLSERV.iBLOBR32K;
DROP PROCEDURE QXMLSERV.iBLOBR65K;
DROP PROCEDURE QXMLSERV.iBLOBR512K;
DROP PROCEDURE QXMLSERV.iBLOBR1M;
DROP PROCEDURE QXMLSERV.iBLOBR5M;
DROP PROCEDURE QXMLSERV.iBLOBR10M;
DROP PROCEDURE QXMLSERV.iBLOBR15M;

DROP PROCEDURE QXMLSERV.iPLUGRC32K;


