DROP PROCEDURE ZENDSVR.iPLUG4K;
DROP PROCEDURE ZENDSVR.iPLUG32K;
DROP PROCEDURE ZENDSVR.iPLUG65K;
DROP PROCEDURE ZENDSVR.iPLUG512K;
DROP PROCEDURE ZENDSVR.iPLUG1M;
DROP PROCEDURE ZENDSVR.iPLUG5M;
DROP PROCEDURE ZENDSVR.iPLUG10M;
DROP PROCEDURE ZENDSVR.iPLUG15M;

DROP PROCEDURE ZENDSVR.iPLUGR4K;
DROP PROCEDURE ZENDSVR.iPLUGR32K;
DROP PROCEDURE ZENDSVR.iPLUGR65K;
DROP PROCEDURE ZENDSVR.iPLUGR512K;
DROP PROCEDURE ZENDSVR.iPLUGR1M;
DROP PROCEDURE ZENDSVR.iPLUGR5M;
DROP PROCEDURE ZENDSVR.iPLUGR10M;
DROP PROCEDURE ZENDSVR.iPLUGR15M;

DROP PROCEDURE ZENDSVR.iBLOB4K;
DROP PROCEDURE ZENDSVR.iBLOB32K;
DROP PROCEDURE ZENDSVR.iBLOB65K;
DROP PROCEDURE ZENDSVR.iBLOB512K;
DROP PROCEDURE ZENDSVR.iBLOB1M;
DROP PROCEDURE ZENDSVR.iBLOB5M;
DROP PROCEDURE ZENDSVR.iBLOB10M;
DROP PROCEDURE ZENDSVR.iBLOB15M;

DROP PROCEDURE ZENDSVR.iBLOBR4K;
DROP PROCEDURE ZENDSVR.iBLOBR32K;
DROP PROCEDURE ZENDSVR.iBLOBR65K;
DROP PROCEDURE ZENDSVR.iBLOBR512K;
DROP PROCEDURE ZENDSVR.iBLOBR1M;
DROP PROCEDURE ZENDSVR.iBLOBR5M;
DROP PROCEDURE ZENDSVR.iBLOBR10M;
DROP PROCEDURE ZENDSVR.iBLOBR15M;

DROP PROCEDURE ZENDSVR.iPLUGRC32K;

