DROP PROCEDURE ZENDSVR6.iPLUG4K;
DROP PROCEDURE ZENDSVR6.iPLUG32K;
DROP PROCEDURE ZENDSVR6.iPLUG65K;
DROP PROCEDURE ZENDSVR6.iPLUG512K;
DROP PROCEDURE ZENDSVR6.iPLUG1M;
DROP PROCEDURE ZENDSVR6.iPLUG5M;
DROP PROCEDURE ZENDSVR6.iPLUG10M;
DROP PROCEDURE ZENDSVR6.iPLUG15M;

DROP PROCEDURE ZENDSVR6.iPLUGR4K;
DROP PROCEDURE ZENDSVR6.iPLUGR32K;
DROP PROCEDURE ZENDSVR6.iPLUGR65K;
DROP PROCEDURE ZENDSVR6.iPLUGR512K;
DROP PROCEDURE ZENDSVR6.iPLUGR1M;
DROP PROCEDURE ZENDSVR6.iPLUGR5M;
DROP PROCEDURE ZENDSVR6.iPLUGR10M;
DROP PROCEDURE ZENDSVR6.iPLUGR15M;

DROP PROCEDURE ZENDSVR6.iBLOB4K;
DROP PROCEDURE ZENDSVR6.iBLOB32K;
DROP PROCEDURE ZENDSVR6.iBLOB65K;
DROP PROCEDURE ZENDSVR6.iBLOB512K;
DROP PROCEDURE ZENDSVR6.iBLOB1M;
DROP PROCEDURE ZENDSVR6.iBLOB5M;
DROP PROCEDURE ZENDSVR6.iBLOB10M;
DROP PROCEDURE ZENDSVR6.iBLOB15M;

DROP PROCEDURE ZENDSVR6.iBLOBR4K;
DROP PROCEDURE ZENDSVR6.iBLOBR32K;
DROP PROCEDURE ZENDSVR6.iBLOBR65K;
DROP PROCEDURE ZENDSVR6.iBLOBR512K;
DROP PROCEDURE ZENDSVR6.iBLOBR1M;
DROP PROCEDURE ZENDSVR6.iBLOBR5M;
DROP PROCEDURE ZENDSVR6.iBLOBR10M;
DROP PROCEDURE ZENDSVR6.iBLOBR15M;

DROP PROCEDURE ZENDSVR6.iPLUGRC32K;


