DROP PROCEDURE POWER_RUBY.iPLUG4K;
DROP PROCEDURE POWER_RUBY.iPLUG32K;
DROP PROCEDURE POWER_RUBY.iPLUG65K;
DROP PROCEDURE POWER_RUBY.iPLUG512K;
DROP PROCEDURE POWER_RUBY.iPLUG1M;
DROP PROCEDURE POWER_RUBY.iPLUG5M;
DROP PROCEDURE POWER_RUBY.iPLUG10M;
DROP PROCEDURE POWER_RUBY.iPLUG15M;

DROP PROCEDURE POWER_RUBY.iPLUGR4K;
DROP PROCEDURE POWER_RUBY.iPLUGR32K;
DROP PROCEDURE POWER_RUBY.iPLUGR65K;
DROP PROCEDURE POWER_RUBY.iPLUGR512K;
DROP PROCEDURE POWER_RUBY.iPLUGR1M;
DROP PROCEDURE POWER_RUBY.iPLUGR5M;
DROP PROCEDURE POWER_RUBY.iPLUGR10M;
DROP PROCEDURE POWER_RUBY.iPLUGR15M;

DROP PROCEDURE POWER_RUBY.iBLOB4K;
DROP PROCEDURE POWER_RUBY.iBLOB32K;
DROP PROCEDURE POWER_RUBY.iBLOB65K;
DROP PROCEDURE POWER_RUBY.iBLOB512K;
DROP PROCEDURE POWER_RUBY.iBLOB1M;
DROP PROCEDURE POWER_RUBY.iBLOB5M;
DROP PROCEDURE POWER_RUBY.iBLOB10M;
DROP PROCEDURE POWER_RUBY.iBLOB15M;

DROP PROCEDURE POWER_RUBY.iBLOBR4K;
DROP PROCEDURE POWER_RUBY.iBLOBR32K;
DROP PROCEDURE POWER_RUBY.iBLOBR65K;
DROP PROCEDURE POWER_RUBY.iBLOBR512K;
DROP PROCEDURE POWER_RUBY.iBLOBR1M;
DROP PROCEDURE POWER_RUBY.iBLOBR5M;
DROP PROCEDURE POWER_RUBY.iBLOBR10M;
DROP PROCEDURE POWER_RUBY.iBLOBR15M;

DROP PROCEDURE POWER_RUBY.iPLUGRC32K;


