DROP PROCEDURE ZENDPHP7.iPLUG4K;
DROP PROCEDURE ZENDPHP7.iPLUG32K;
DROP PROCEDURE ZENDPHP7.iPLUG65K;
DROP PROCEDURE ZENDPHP7.iPLUG512K;
DROP PROCEDURE ZENDPHP7.iPLUG1M;
DROP PROCEDURE ZENDPHP7.iPLUG5M;
DROP PROCEDURE ZENDPHP7.iPLUG10M;
DROP PROCEDURE ZENDPHP7.iPLUG15M;

DROP PROCEDURE ZENDPHP7.iPLUGR4K;
DROP PROCEDURE ZENDPHP7.iPLUGR32K;
DROP PROCEDURE ZENDPHP7.iPLUGR65K;
DROP PROCEDURE ZENDPHP7.iPLUGR512K;
DROP PROCEDURE ZENDPHP7.iPLUGR1M;
DROP PROCEDURE ZENDPHP7.iPLUGR5M;
DROP PROCEDURE ZENDPHP7.iPLUGR10M;
DROP PROCEDURE ZENDPHP7.iPLUGR15M;

DROP PROCEDURE ZENDPHP7.iBLOB4K;
DROP PROCEDURE ZENDPHP7.iBLOB32K;
DROP PROCEDURE ZENDPHP7.iBLOB65K;
DROP PROCEDURE ZENDPHP7.iBLOB512K;
DROP PROCEDURE ZENDPHP7.iBLOB1M;
DROP PROCEDURE ZENDPHP7.iBLOB5M;
DROP PROCEDURE ZENDPHP7.iBLOB10M;
DROP PROCEDURE ZENDPHP7.iBLOB15M;

DROP PROCEDURE ZENDPHP7.iBLOBR4K;
DROP PROCEDURE ZENDPHP7.iBLOBR32K;
DROP PROCEDURE ZENDPHP7.iBLOBR65K;
DROP PROCEDURE ZENDPHP7.iBLOBR512K;
DROP PROCEDURE ZENDPHP7.iBLOBR1M;
DROP PROCEDURE ZENDPHP7.iBLOBR5M;
DROP PROCEDURE ZENDPHP7.iBLOBR10M;
DROP PROCEDURE ZENDPHP7.iBLOBR15M;

DROP PROCEDURE ZENDPHP7.iPLUGRC32K;


