DROP PROCEDURE XMLSERVICE.iPLUG4K;
DROP PROCEDURE XMLSERVICE.iPLUG32K;
DROP PROCEDURE XMLSERVICE.iPLUG65K;
DROP PROCEDURE XMLSERVICE.iPLUG512K;
DROP PROCEDURE XMLSERVICE.iPLUG1M;
DROP PROCEDURE XMLSERVICE.iPLUG5M;
DROP PROCEDURE XMLSERVICE.iPLUG10M;
DROP PROCEDURE XMLSERVICE.iPLUG15M;

DROP PROCEDURE XMLSERVICE.iPLUGR4K;
DROP PROCEDURE XMLSERVICE.iPLUGR32K;
DROP PROCEDURE XMLSERVICE.iPLUGR65K;
DROP PROCEDURE XMLSERVICE.iPLUGR512K;
DROP PROCEDURE XMLSERVICE.iPLUGR1M;
DROP PROCEDURE XMLSERVICE.iPLUGR5M;
DROP PROCEDURE XMLSERVICE.iPLUGR10M;
DROP PROCEDURE XMLSERVICE.iPLUGR15M;

DROP PROCEDURE XMLSERVICE.iBLOB4K;
DROP PROCEDURE XMLSERVICE.iBLOB32K;
DROP PROCEDURE XMLSERVICE.iBLOB65K;
DROP PROCEDURE XMLSERVICE.iBLOB512K;
DROP PROCEDURE XMLSERVICE.iBLOB1M;
DROP PROCEDURE XMLSERVICE.iBLOB5M;
DROP PROCEDURE XMLSERVICE.iBLOB10M;
DROP PROCEDURE XMLSERVICE.iBLOB15M;

DROP PROCEDURE XMLSERVICE.iBLOBR4K;
DROP PROCEDURE XMLSERVICE.iBLOBR32K;
DROP PROCEDURE XMLSERVICE.iBLOBR65K;
DROP PROCEDURE XMLSERVICE.iBLOBR512K;
DROP PROCEDURE XMLSERVICE.iBLOBR1M;
DROP PROCEDURE XMLSERVICE.iBLOBR5M;
DROP PROCEDURE XMLSERVICE.iBLOBR10M;
DROP PROCEDURE XMLSERVICE.iBLOBR15M;

DROP PROCEDURE XMLSERVICE.iPLUGRC32K;


