CREATE OR REPLACE PROCEDURE XMLSERVICE.iPLUG4K(
IN IPC CHAR(1024), IN CTL CHAR(1024),
IN CI CLOB(4K), OUT C0 CLOB(4K))
LANGUAGE RPGLE 
NOT DETERMINISTIC
MODIFIES SQL DATA
EXTERNAL NAME 'XMLSERVICE/XMLSTOREDP(iPLUG4K)'
PARAMETER STYLE GENERAL;

CREATE OR REPLACE PROCEDURE XMLSERVICE.iPLUG32K(
IN IPC CHAR(1024), IN CTL CHAR(1024), 
IN CI CLOB(32K), OUT CO CLOB(32K)) 
LANGUAGE RPGLE NOT DETERMINISTIC 
MODIFIES SQL DATA 
EXTERNAL NAME 'XMLSERVICE/XMLSTOREDP(iPLUG32K)' 
PARAMETER STYLE GENERAL;

CREATE OR REPLACE PROCEDURE XMLSERVICE.iPLUG65K(
IN IPC CHAR(1024), IN CTL CHAR(1024), 
IN CI CLOB(65K), OUT CO CLOB(65K)) 
LANGUAGE RPGLE NOT DETERMINISTIC 
MODIFIES SQL DATA 
EXTERNAL NAME 'XMLSERVICE/XMLSTOREDP(iPLUG65K)' 
PARAMETER STYLE GENERAL;

CREATE OR REPLACE PROCEDURE XMLSERVICE.iPLUG512K(
IN IPC CHAR(1024), IN CTL CHAR(1024), 
IN CI CLOB(512K), OUT CO CLOB(512K)) 
LANGUAGE RPGLE NOT DETERMINISTIC 
MODIFIES SQL DATA 
EXTERNAL NAME 'XMLSERVICE/XMLSTOREDP(iPLUG512K)' 
PARAMETER STYLE GENERAL;

CREATE OR REPLACE PROCEDURE XMLSERVICE.iPLUG1M(
IN IPC CHAR(1024), IN CTL CHAR(1024), 
IN CI CLOB(1M), OUT CO CLOB(1M)) 
LANGUAGE RPGLE NOT DETERMINISTIC 
MODIFIES SQL DATA 
EXTERNAL NAME 'XMLSERVICE/XMLSTOREDP(iPLUG1M)' 
PARAMETER STYLE GENERAL;

CREATE OR REPLACE PROCEDURE XMLSERVICE.iPLUG5M(
IN IPC CHAR(1024), IN CTL CHAR(1024), 
IN CI CLOB(5M), OUT CO CLOB(5M)) 
LANGUAGE RPGLE NOT DETERMINISTIC 
MODIFIES SQL DATA 
EXTERNAL NAME 'XMLSERVICE/XMLSTOREDP(iPLUG5M)' 
PARAMETER STYLE GENERAL;

CREATE OR REPLACE PROCEDURE XMLSERVICE.iPLUG10M(
IN IPC CHAR(1024), IN CTL CHAR(1024), 
IN CI CLOB(10M), OUT CO CLOB(10M)) 
LANGUAGE RPGLE NOT DETERMINISTIC 
MODIFIES SQL DATA 
EXTERNAL NAME 'XMLSERVICE/XMLSTOREDP(iPLUG10M)' 
PARAMETER STYLE GENERAL;

CREATE OR REPLACE PROCEDURE XMLSERVICE.iPLUG15M(
IN IPC CHAR(1024), IN CTL CHAR(1024), 
IN CI CLOB(15M), OUT CO CLOB(15M)) 
LANGUAGE RPGLE NOT DETERMINISTIC 
MODIFIES SQL DATA 
EXTERNAL NAME 'XMLSERVICE/XMLSTOREDP(iPLUG15M)' 
PARAMETER STYLE GENERAL;


CREATE OR REPLACE PROCEDURE XMLSERVICE.iPLUGR4K(
IN IPC CHAR(1024), IN CTL CHAR(1024), 
IN CI CLOB(4K)) 
LANGUAGE RPGLE NOT DETERMINISTIC 
MODIFIES SQL DATA 
Result Sets 1 
EXTERNAL NAME 'XMLSERVICE/XMLSTOREDP(iPLUGR4K)' 
PARAMETER STYLE GENERAL;

CREATE OR REPLACE PROCEDURE XMLSERVICE.iPLUGR32K(
IN IPC CHAR(1024), IN CTL CHAR(1024), 
IN CI CLOB(32K)) 
LANGUAGE RPGLE NOT DETERMINISTIC 
MODIFIES SQL DATA 
Result Sets 1 
EXTERNAL NAME 'XMLSERVICE/XMLSTOREDP(iPLUGR32K)' 
PARAMETER STYLE GENERAL;

CREATE OR REPLACE PROCEDURE XMLSERVICE.iPLUGR65K(
IN IPC CHAR(1024), IN CTL CHAR(1024), 
IN CI CLOB(65K)) 
LANGUAGE RPGLE NOT DETERMINISTIC 
MODIFIES SQL DATA 
Result Sets 1 
EXTERNAL NAME 'XMLSERVICE/XMLSTOREDP(iPLUGR65K)' 
PARAMETER STYLE GENERAL;

CREATE OR REPLACE PROCEDURE XMLSERVICE.iPLUGR512K(
IN IPC CHAR(1024), IN CTL CHAR(1024), 
IN CI CLOB(512K)) 
LANGUAGE RPGLE NOT DETERMINISTIC 
MODIFIES SQL DATA 
Result Sets 1 
EXTERNAL NAME 'XMLSERVICE/XMLSTOREDP(iPLUGR512K)' 
PARAMETER STYLE GENERAL;

CREATE OR REPLACE PROCEDURE XMLSERVICE.iPLUGR1M(
IN IPC CHAR(1024), IN CTL CHAR(1024), 
IN CI CLOB(1M)) 
LANGUAGE RPGLE NOT DETERMINISTIC 
MODIFIES SQL DATA 
Result Sets 1 
EXTERNAL NAME 'XMLSERVICE/XMLSTOREDP(iPLUGR1M)' 
PARAMETER STYLE GENERAL;

CREATE OR REPLACE PROCEDURE XMLSERVICE.iPLUGR5M(
IN IPC CHAR(1024), IN CTL CHAR(1024), 
IN CI CLOB(5M)) 
LANGUAGE RPGLE NOT DETERMINISTIC 
MODIFIES SQL DATA 
Result Sets 1 
EXTERNAL NAME 'XMLSERVICE/XMLSTOREDP(iPLUGR5M)' 
PARAMETER STYLE GENERAL;

CREATE OR REPLACE PROCEDURE XMLSERVICE.iPLUGR10M(
IN IPC CHAR(1024), IN CTL CHAR(1024), 
IN CI CLOB(10M)) 
LANGUAGE RPGLE NOT DETERMINISTIC 
MODIFIES SQL DATA 
Result Sets 1 
EXTERNAL NAME 'XMLSERVICE/XMLSTOREDP(iPLUGR10M)' 
PARAMETER STYLE GENERAL;

CREATE OR REPLACE PROCEDURE XMLSERVICE.iPLUGR15M(
IN IPC CHAR(1024), IN CTL CHAR(1024), 
IN CI CLOB(15M)) 
LANGUAGE RPGLE NOT DETERMINISTIC 
MODIFIES SQL DATA 
Result Sets 1 
EXTERNAL NAME 'XMLSERVICE/XMLSTOREDP(iPLUGR15M)' 
PARAMETER STYLE GENERAL;


CREATE OR REPLACE PROCEDURE XMLSERVICE.iBLOB512K(
IN IPC CHAR(1024), IN CTL CHAR(1024), 
IN CI BLOB(512K), OUT CO BLOB(512K)) 
LANGUAGE RPGLE NOT DETERMINISTIC 
MODIFIES SQL DATA 
EXTERNAL NAME 'XMLSERVICE/XMLSTOREDP(iPLUG512K)' 
PARAMETER STYLE GENERAL;

CREATE OR REPLACE PROCEDURE XMLSERVICE.iBLOB1M(
IN IPC CHAR(1024), IN CTL CHAR(1024), 
IN CI BLOB(1M), OUT CO BLOB(1M)) 
LANGUAGE RPGLE NOT DETERMINISTIC 
MODIFIES SQL DATA 
EXTERNAL NAME 'XMLSERVICE/XMLSTOREDP(iPLUG1M)' 
PARAMETER STYLE GENERAL;

CREATE OR REPLACE PROCEDURE XMLSERVICE.iBLOB5M(
IN IPC CHAR(1024), IN CTL CHAR(1024), 
IN CI BLOB(5M), OUT CO BLOB(5M)) 
LANGUAGE RPGLE NOT DETERMINISTIC 
MODIFIES SQL DATA 
EXTERNAL NAME 'XMLSERVICE/XMLSTOREDP(iPLUG5M)' 
PARAMETER STYLE GENERAL;

CREATE OR REPLACE PROCEDURE XMLSERVICE.iBLOB10M(
IN IPC CHAR(1024), IN CTL CHAR(1024), 
IN CI BLOB(10M), OUT CO BLOB(10M)) 
LANGUAGE RPGLE NOT DETERMINISTIC 
MODIFIES SQL DATA 
EXTERNAL NAME 'XMLSERVICE/XMLSTOREDP(iPLUG10M)' 
PARAMETER STYLE GENERAL;

CREATE OR REPLACE PROCEDURE XMLSERVICE.iBLOB15M(
IN IPC CHAR(1024), IN CTL CHAR(1024), 
IN CI BLOB(15M), OUT CO BLOB(15M)) 
LANGUAGE RPGLE NOT DETERMINISTIC 
MODIFIES SQL DATA 
EXTERNAL NAME 'XMLSERVICE/XMLSTOREDP(iPLUG15M)' 
PARAMETER STYLE GENERAL;

CREATE OR REPLACE PROCEDURE XMLSERVICE.iBLOBR512K(
IN IPC CHAR(1024), IN CTL CHAR(1024), 
IN CI BLOB(512K)) 
LANGUAGE RPGLE NOT DETERMINISTIC 
MODIFIES SQL DATA 
Result Sets 1 
EXTERNAL NAME 'XMLSERVICE/XMLSTOREDP(iPLUGR512K)' 
PARAMETER STYLE GENERAL;

CREATE OR REPLACE PROCEDURE XMLSERVICE.iBLOBR1M(
IN IPC CHAR(1024), IN CTL CHAR(1024), 
IN CI BLOB(1M)) 
LANGUAGE RPGLE NOT DETERMINISTIC 
MODIFIES SQL DATA 
Result Sets 1 
EXTERNAL NAME 'XMLSERVICE/XMLSTOREDP(iPLUGR1M)' 
PARAMETER STYLE GENERAL;

CREATE OR REPLACE PROCEDURE XMLSERVICE.iBLOBR5M(
IN IPC CHAR(1024), IN CTL CHAR(1024), 
IN CI BLOB(5M)) 
LANGUAGE RPGLE NOT DETERMINISTIC 
MODIFIES SQL DATA 
Result Sets 1 
EXTERNAL NAME 'XMLSERVICE/XMLSTOREDP(iPLUGR5M)' 
PARAMETER STYLE GENERAL;

CREATE OR REPLACE PROCEDURE XMLSERVICE.iBLOBR10M(
IN IPC CHAR(1024), IN CTL CHAR(1024), 
IN CI BLOB(10M)) 
LANGUAGE RPGLE NOT DETERMINISTIC 
MODIFIES SQL DATA 
Result Sets 1 
EXTERNAL NAME 'XMLSERVICE/XMLSTOREDP(iPLUGR10M)' 
PARAMETER STYLE GENERAL;

CREATE OR REPLACE PROCEDURE XMLSERVICE.iBLOBR15M(
IN IPC CHAR(1024), IN CTL CHAR(1024), 
IN CI BLOB(15M)) 
LANGUAGE RPGLE NOT DETERMINISTIC 
MODIFIES SQL DATA 
Result Sets 1 
EXTERNAL NAME 'XMLSERVICE/XMLSTOREDP(iPLUGR15M)' 
PARAMETER STYLE GENERAL;

CREATE OR REPLACE PROCEDURE XMLSERVICE.iPLUGRC32K(
IN IPC CHAR(1024), IN CTL CHAR(1024), 
IN CI VARCHAR(32700), IN CNT INTEGER) 
LANGUAGE RPGLE NOT DETERMINISTIC 
MODIFIES SQL DATA 
Result Sets 1 
EXTERNAL NAME 'XMLSERVICE/XMLSTOREDP(iPLUGRC32K)' 
PARAMETER STYLE GENERAL;
