PGM
CHGLIBL LIBL(XMLSERVICE) CURLIB(XMLSERVICE)

CRTRPGMOD MODULE(XMLSERVICE/ZZSRV6) SRCFILE(XMLSERVICE/QRPGLESRC) +
  DBGVIEW(*SOURCE) OUTPUT(*PRINT) REPLACE(*YES)
CRTSRVPGM SRVPGM(XMLSERVICE/ZZSRV6) MODULE(XMLSERVICE/ZZSRV6) +
  EXPORT(*ALL) ACTGRP(*CALLER)
DLTMOD MODULE(XMLSERVICE/ZZSRV6)

CRTRPGMOD MODULE(XMLSERVICE/ZZBIGBOY) SRCFILE(XMLSERVICE/QRPGLESRC) +
  DBGVIEW(*SOURCE) OUTPUT(*PRINT) REPLACE(*YES)
CRTPGM PGM(XMLSERVICE/ZZBIGBOY) ACTGRP(BIGBOY1)
DLTMOD MODULE(XMLSERVICE/ZZBIGBOY)

CRTSQLRPGI OBJ(XMLSERVICE/ZZJAVA) SRCFILE(XMLSERVICE/QRPGLESRC) +
  OBJTYPE(*MODULE) OUTPUT(*PRINT) DBGVIEW(*SOURCE) REPLACE(*YES)
CRTPGM PGM(XMLSERVICE/ZZJAVA) ACTGRP(*CALLER)
DLTMOD MODULE(XMLSERVICE/ZZJAVA)

CRTRPGMOD MODULE(XMLSERVICE/ZZJAVA2) SRCFILE(XMLSERVICE/QRPGLESRC) +
  DBGVIEW(*SOURCE) OUTPUT(*PRINT) REPLACE(*YES)
CRTPGM PGM(XMLSERVICE/ZZJAVA2) ACTGRP(*CALLER)
DLTMOD MODULE(XMLSERVICE/ZZJAVA2)


ENDPGM
